name: energize
channels:
  - conda-forge
  - pytorch
  - nvidia/label/cuda-12.1.0
  - defaults

dependencies:
  - python=3.10
  - cuda=12.1.0=0
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - torchmetrics=1.1.1
  - scikit-learn=1.3.0
  - dill=0.3.7
  - jsonschema=4.4.0
  - PyYAML=6.0.1
  - versioneer=0.29
  - llvm-openmp<16
  - coverage=7.3.2
  - pytest=7.4.2
  - parameterized=0.9.0
  - pip
  - pip:
    - pyJoules[nvidia]==0.5.1
    - ipython